package io.github.blad3mak3r.slash.registry

import net.dv8tion.jda.api.Permission
import io.github.blad3mak3r.slash.annotations.PermissionTarget

/**
 * Holds the compiled permissions requirement for a command handler.
 *
 * Generated by the KSP processor from the `@Permissions` annotation and stored
 * as a field on the generated registrar — no reflection at runtime.
 *
 * @param permissions The required [Permission]s.
 * @param target Whether [PermissionTarget.USER] or [PermissionTarget.BOT] is checked.
 */
data class PermissionsConfig(
    val permissions: Array<Permission>,
    val target: PermissionTarget
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is PermissionsConfig) return false
        return target == other.target && permissions.contentEquals(other.permissions)
    }

    override fun hashCode(): Int {
        var result = permissions.contentHashCode()
        result = 31 * result + target.hashCode()
        return result
    }
}
